sudo: required
language: python
python:
  - "3.5"
  - "3.6"
services:
  - docker
cache: pip
install:
  - pip install bioblend==0.9.0
  - pip install coveralls
  - python setup.py install
before_script:
  - docker pull askomics/virtuoso
  - docker pull bgruening/galaxy-stable
  - docker pull askomics/fedx4askomics:rdf4j
  - docker pull xgaia/corese
  - sudo docker run --name corese -p 5050:8080 -d xgaia/corese
  - sudo docker run --name fedx -p 4040:4040 -d askomics/fedx4askomics:rdf4j
  - sudo docker run -d --name virtuoso -p 8890:8890 -e DBA_PASSWORD=dba -e SPARQL_UPDATE=true -e DEFAULT_GRAPH=http://localhost:8890/DAV --net="host" -t askomics/virtuoso
  - sudo docker run -d --name virtuoso2 -p 8891:8890 -e DBA_PASSWORD=dba -e SPARQL_UPDATE=true -e DEFAULT_GRAPH=http://localhost:8891/DAV --net="host" -t askomics/virtuoso
  - sudo docker run -d --name galaxy -p 8080:80 bgruening/galaxy-stable
  - sleep 1m
script:
  - python setup.py nosetests
after_success:
  coveralls
